### ISSUE TITLE
Poggyy

### ISSUE THREAD

**Issue by Bexpg-0** [Alexander9673/Pogtopia#1]
Trash..

**Comment by Mempler** [comment]
^ @Alexander9673 i recommend marking this issue as invalid and prob report him for creating an spam issue

**Comment by Alexander9673** [comment]
Reported 👍

**Comment by Bexpg-0** [comment]
> ^ @Alexander9673 i recommend marking this issue as invalid and prob report him for creating an spam issue

Oh no i scared wksskkskkwkq2k

**Comment by HanSolu7** [comment]
shut up just shut the fuck up be quiet for several days

**Comment by Alexander9673** [comment]
dont worry, he's already banned from the repo

**Comment by HanSolu7** [comment]
bout to face 3 alts just because of getting banned from the repo let's go
